[package]
name = "synaptic-pdf"
description = "PDF document loader for Synaptic"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
synaptic-core = { version = "0.2", path = "../synaptic-core" }
pdf-extract = "0.7"

[dev-dependencies]
tokio.workspace = true
