[package]
name = "evaluation"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
tokio.workspace = true
synaptic = { version = "0.1.0", path = "../../crates/synapse", features = ["eval"] }
