[package]
name = "tool_calling_basic"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
synaptic = { version = "0.2", path = "../../crates/synaptic", features = ["tools", "macros"] }
synaptic-core = { workspace = true }
synaptic-macros = { workspace = true }
