[package]
name = "synaptic-tools"
description = "Tool registry and execution: ToolRegistry, SerialToolExecutor, ParallelToolExecutor"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures.workspace = true
reqwest.workspace = true
urlencoding = "2"
meval = "0.2"
synaptic-core = { version = "0.2", path = "../synaptic-core" }

[dev-dependencies]
synaptic-macros = { workspace = true }
