[package]
name = "lcel_chain"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
tokio.workspace = true
synaptic = { version = "0.2", path = "../../crates/synaptic", features = ["runnables"] }
synaptic-core = { workspace = true }
synaptic-macros = { workspace = true }
synaptic-runnables = { workspace = true }
