[package]
name = "macros_showcase"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
synaptic-core = { version = "0.2", path = "../../crates/synaptic-core" }
synaptic-macros = { version = "0.2", path = "../../crates/synaptic-macros" }
synaptic-middleware = { version = "0.2", path = "../../crates/synaptic-middleware" }
synaptic-runnables = { version = "0.2", path = "../../crates/synaptic-runnables" }
