[package]
name = "prompt_parser_chain"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
tokio.workspace = true
synapse = { path = "../../crates/synapse", features = ["models", "prompts", "parsers"] }
