[package]
name = "memory_strategy"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
tokio.workspace = true
synaptic = { version = "0.2", path = "../../crates/synaptic", features = ["model-utils", "memory"] }
