[package]
name = "caching"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
tokio.workspace = true
synaptic = { version = "0.2", path = "../../crates/synaptic", features = ["cache", "model-utils"] }
