[book]
title = "Synaptic"
description = "A Rust agent framework with LangChain-compatible architecture"
authors = ["Synaptic Contributors"]
language = "en"
src = "src"

[build]
build-dir = "../../dist/en"
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/dnw3/synaptic"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/dnw3/synaptic/edit/main/docs/book/en/src/{path}"
additional-css = ["custom.css"]
additional-js = ["lang-switcher.js"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
runnable = false

[output.html.search]
enable = true
limit-results = 20
